name: Purge Camo cache
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}  # allow manual runs

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: kevincobain2000/action-camo-purge@v1
